import uuid
from datetime import datetime
from typing import Any, Optional
from pydantic import BaseModel, Field
from .enums import ActionSource, ActionType, ConsentLevel, ImpactLevel, NotificationChannel

class Action(BaseModel):
    """
    Action generated by either the rule engine or Bedrock.
    """
    action_id: str = Field(
        default_factory=lambda: f"act_{uuid.uuid4().hex[:12]}"
    )
    household_id: str
    action_type: ActionType
    source: ActionSource = Field(..., description="Must explicitly state the source (Rule Engine, Bedrock, etc.)")

    # Target configuration
    device_id: Optional[str] = None
    command: Optional[str] = None
    target_member_ids: list[str] = Field(default_factory=list)

    # Notification settings
    message: Optional[str] = None
    channel: Optional[NotificationChannel] = None
    language: str = "hindi"

    # Traceability
    rule_id: Optional[str] = None
    pattern_id: Optional[str] = None
    event_id: Optional[str] = None
    bedrock_request_id: Optional[str] = None

    # Action planning
    consent_level: ConsentLevel = ConsentLevel.SUGGEST
    idempotency_key: Optional[str] = None
    scheduled_time: Optional[datetime] = None
    timer_minutes: Optional[int] = None

    # Execution status
    dispatched: bool = False
    dispatch_time: Optional[datetime] = None
    result: Optional[str] = None

    created_at: datetime = Field(default_factory=datetime.utcnow)

class CommandResult(BaseModel):
    """Result from the device command bus."""
    action_id: str
    device_id: Optional[str] = None
    command: Optional[str] = None
    success: bool
    pre_state: Optional[dict[str, Any]] = None
    post_state: Optional[dict[str, Any]] = None
    error: Optional[str] = None
    latency_ms: float = 0.0
    idempotency_key: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.utcnow)

class Notification(BaseModel):
    """User notification details."""
    notification_id: str = Field(
        default_factory=lambda: f"ntf_{uuid.uuid4().hex[:12]}"
    )
    household_id: str
    target_member_ids: list[str]
    channel: NotificationChannel
    language: str = "hindi"
    message: str
    title: Optional[str] = None
    priority: ImpactLevel = ImpactLevel.MEDIUM
    source: ActionSource

    # Context for rendering
    action_id: Optional[str] = None
    event_id: Optional[str] = None
    device_id: Optional[str] = None

    # Delivery status
    sent: bool = False
    sent_at: Optional[datetime] = None
    error: Optional[str] = None
    rate_limited: bool = False

    created_at: datetime = Field(default_factory=datetime.utcnow)
